/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visual;

import br.com.controle.Controle;
import br.com.modelo.FuncionaBean;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author raul
 */
public class AcessoUsuario extends javax.swing.JDialog {

    FuncionaBean funcionaBean = new FuncionaBean();
    Controle controle = new Controle();

    public FuncionaBean getFuncionaBean() {
        return funcionaBean;
    }

    public void setFuncionaBean(FuncionaBean funcionaBean) {
        this.funcionaBean = funcionaBean;
    }

    /**
     * Creates new form AcessoUsuario
     */
    public AcessoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //---------------
        //papel de parede
        if (Caixa.ConfiguracaoBean.getPapelParede() != null) {

            File f = new File(Caixa.ConfiguracaoBean.getPapelParede());

            try {

                BufferedImage tmpImagen = ImageIO.read(f);
                ImagemFundoPanel fondo = new ImagemFundoPanel(tmpImagen);
                lydPrincipal.setBorder(fondo);

                ftfUsuario.requestFocus();

            } catch (Exception ex) {
                Loggin.logDiarioExcecao(ex, true);
            }
        }
        //---------------
        ImageIcon icone = new javax.swing.ImageIcon(Constantes.SH_ICONE);
        setIconImage(icone.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lydPrincipal = new javax.swing.JLayeredPane();
        panelFaixa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        ftfUsuario = new javax.swing.JFormattedTextField();
        ftfSenha = new javax.swing.JPasswordField();
        lydBotao = new javax.swing.JLayeredPane();
        botaoCancelar = new javax.swing.JButton();
        botaoOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acesso de usuario");

        panelFaixa.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Acesso de Usuario");

        javax.swing.GroupLayout panelFaixaLayout = new javax.swing.GroupLayout(panelFaixa);
        panelFaixa.setLayout(panelFaixaLayout);
        panelFaixaLayout.setHorizontalGroup(
            panelFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFaixaLayout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
        );
        panelFaixaLayout.setVerticalGroup(
            panelFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFaixaLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jLabel8)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        labelUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelUsuario.setText("Usuario (código):");

        labelSenha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelSenha.setText("Senha:");

        ftfUsuario.setText("1");
        ftfUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ftfUsuario.setMinimumSize(new java.awt.Dimension(240, 40));
        ftfUsuario.setPreferredSize(new java.awt.Dimension(240, 40));
        ftfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftfUsuarioMouseClicked(evt);
            }
        });
        ftfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfUsuarioKeyPressed(evt);
            }
        });

        ftfSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ftfSenha.setText("1");
        ftfSenha.setMinimumSize(new java.awt.Dimension(240, 40));
        ftfSenha.setPreferredSize(new java.awt.Dimension(240, 40));
        ftfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfSenhaActionPerformed(evt);
            }
        });
        ftfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfSenhaKeyPressed(evt);
            }
        });

        lydBotao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lydBotao.setMinimumSize(new java.awt.Dimension(100, 45));
        lydBotao.setPreferredSize(new java.awt.Dimension(266, 45));
        lydBotao.setLayout(new java.awt.GridBagLayout());

        botaoCancelar.setText("Cancelar");
        botaoCancelar.setMinimumSize(new java.awt.Dimension(100, 30));
        botaoCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        lydBotao.setLayer(botaoCancelar, 1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        lydBotao.add(botaoCancelar, gridBagConstraints);

        botaoOk.setText("Ok");
        botaoOk.setMinimumSize(new java.awt.Dimension(100, 30));
        botaoOk.setPreferredSize(new java.awt.Dimension(100, 30));
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });
        lydBotao.setLayer(botaoOk, 1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        lydBotao.add(botaoOk, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setText("Config Data Source");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        lydBotao.add(jButton1, gridBagConstraints);

        lydPrincipal.setLayer(panelFaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lydPrincipal.setLayer(labelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lydPrincipal.setLayer(labelSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lydPrincipal.setLayer(ftfUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lydPrincipal.setLayer(ftfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lydPrincipal.setLayer(lydBotao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lydPrincipalLayout = new javax.swing.GroupLayout(lydPrincipal);
        lydPrincipal.setLayout(lydPrincipalLayout);
        lydPrincipalLayout.setHorizontalGroup(
            lydPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lydPrincipalLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(lydPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario)
                    .addComponent(labelSenha)
                    .addComponent(ftfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(lydBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lydPrincipalLayout.setVerticalGroup(
            lydPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lydPrincipalLayout.createSequentialGroup()
                .addComponent(panelFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lydBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lydPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lydPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed

        funcionaBean = null;
        dispose();

    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed

        try {

            if (ftfUsuario.getText() == null || ftfUsuario.getText().isEmpty()) {
                ftfUsuario.requestFocus();
                return;
            }

            if (ftfSenha.getPassword() == null || ftfSenha.getPassword().length == 0) {
                ftfSenha.requestFocus();
                return;
            }

            Integer fuCodigo = Integer.parseInt(ftfUsuario.getText().trim());
            String senha = String.valueOf(ftfSenha.getPassword());
            funcionaBean = controle.acessarUsuario(fuCodigo, senha);
            if (funcionaBean == null || funcionaBean.getFucodigo() == null) {
                JOptionPane.showMessageDialog(this, "Acesso negado!", Constantes.AVISO_SISTEMA, JOptionPane.INFORMATION_MESSAGE);
            }

            //----------------------            
            dispose();

        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }

    }//GEN-LAST:event_botaoOkActionPerformed

    private void ftfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //pressionou ENTER
            botaoOk.requestFocus();
        }
    }//GEN-LAST:event_ftfSenhaKeyPressed

    private void ftfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfSenhaActionPerformed

    private void ftfUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftfUsuarioMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ftfUsuarioMouseClicked

    private void ftfUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //pressionou ENTER
            ftfSenha.requestFocus();
        }
    }//GEN-LAST:event_ftfUsuarioKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConfigurarAcessoBD configurarAcesso = new ConfigurarAcessoBD(new JFrame(), true);
        configurarAcesso.setResizable(false);
        configurarAcesso.setModal(true);
        configurarAcesso.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AcessoUsuario dialog = new AcessoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JPasswordField ftfSenha;
    private javax.swing.JFormattedTextField ftfUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLayeredPane lydBotao;
    private javax.swing.JLayeredPane lydPrincipal;
    private javax.swing.JPanel panelFaixa;
    // End of variables declaration//GEN-END:variables
}
