/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visual;

import br.com.controle.Controle;
import br.com.modelo.ClienPdvBean;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul
 */
public class ConsultarClientes extends javax.swing.JDialog {

    private final Controle controle = new Controle();
    private ClienPdvBean clienPdvBean = new ClienPdvBean();
    List<ClienPdvBean> listaClienPdvBean = new ArrayList<>();

    public ClienPdvBean getMaterPdvBean() {
        return clienPdvBean;
    }

    /**
     * Creates new form ConsultarItens
     */
    public ConsultarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ImageIcon icone = new javax.swing.ImageIcon(Constantes.SH_ICONE);
        setIconImage(icone.getImage());

        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); //DESABILITAR tb a função do X do JDialog, para que só seja possível cancelar clicando no seu botão, coloque tb. esse código: 
        CancelarAction cancelarAction = new CancelarAction();
        panelComponentes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelarAction");
        panelComponentes.getActionMap().put("cancelarAction", cancelarAction);

        SelecionarAction selecionarAction = new SelecionarAction();
        panelComponentes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "selecionarAction");
        panelComponentes.getActionMap().put("selecionarAction", selecionarAction);

        try {
            
            jLabel7.setText("");

            formatarTabelaItens();

            //------------------------
            obterPadraoPesquisa("ABERTURA");
        } catch (IOException ex) {
            Loggin.logDiarioExcecao(ex, true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelComponentes = new javax.swing.JPanel();
        panelFiltros = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboConsultar = new javax.swing.JComboBox();
        ftfPesquisar = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ftfTotalVencido = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ftfTotalAvencer = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ftfTotalApagar = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfLimiteCredito = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        panelBotao = new javax.swing.JPanel();
        botaoSelecionar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta de Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro da Consulta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N
        panelFiltros.setPreferredSize(new java.awt.Dimension(1024, 720));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(520, 15));
        jLabel7.setMinimumSize(new java.awt.Dimension(520, 15));

        comboConsultar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Apelido", "Cpf", "Cgc", "Cód. Interno" }));
        comboConsultar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboConsultarItemStateChanged(evt);
            }
        });

        ftfPesquisar.setText(" ");
        ftfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfPesquisarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel1.setText("Pressione ENTER para consulta");

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Consulta Ordenada");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Consulta \"Palavra Chave\"");

        jPanel2.setMinimumSize(new java.awt.Dimension(1012, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(1012, 540));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 390));

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "CGC", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaItensMouseClicked(evt);
            }
        });
        tabelaItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaItensKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaItens);

        jTabbedPane1.addTab("Clientes", jScrollPane1);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nome Cliente");

        jLabel3.setText("Total Vencido:");

        ftfTotalVencido.setEditable(false);
        ftfTotalVencido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfTotalVencido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftfTotalVencido.setMinimumSize(new java.awt.Dimension(150, 30));
        ftfTotalVencido.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel4.setText("Total a Vencer");

        ftfTotalAvencer.setEditable(false);
        ftfTotalAvencer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfTotalAvencer.setText(" ");
        ftfTotalAvencer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftfTotalAvencer.setMinimumSize(new java.awt.Dimension(150, 30));
        ftfTotalAvencer.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel5.setText("Total a Pagar:");

        ftfTotalApagar.setEditable(false);
        ftfTotalApagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfTotalApagar.setText(" ");
        ftfTotalApagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftfTotalApagar.setMinimumSize(new java.awt.Dimension(150, 30));
        ftfTotalApagar.setPreferredSize(new java.awt.Dimension(150, 30));
        ftfTotalApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfTotalApagarActionPerformed(evt);
            }
        });

        jLabel6.setText("Limite de Crédito:");

        ftfLimiteCredito.setEditable(false);
        ftfLimiteCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfLimiteCredito.setText(" ");
        ftfLimiteCredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ftfLimiteCredito.setMinimumSize(new java.awt.Dimension(150, 30));
        ftfLimiteCredito.setPreferredSize(new java.awt.Dimension(150, 30));

        jButton2.setText("Atualizar");
        jButton2.setMinimumSize(new java.awt.Dimension(75, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfTotalApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfTotalAvencer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfTotalVencido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 692, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfTotalVencido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfTotalAvencer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftfTotalApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de crédito", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFiltrosLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ftfPesquisar))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );

        panelBotao.setLayout(new java.awt.GridBagLayout());

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.setMaximumSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.setMinimumSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.setPreferredSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelBotao.add(botaoSelecionar, gridBagConstraints);

        jButton3.setText(" Cancelar");
        jButton3.setMaximumSize(new java.awt.Dimension(150, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelBotao.add(jButton3, gridBagConstraints);

        javax.swing.GroupLayout panelComponentesLayout = new javax.swing.GroupLayout(panelComponentes);
        panelComponentes.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cancelar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void ftfPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfPesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //pressionou ENTER
            try {
                consultar();
            } catch (Exception ex) {
                Loggin.logDiarioExcecao(ex, true);
            }
        }
    }//GEN-LAST:event_ftfPesquisarKeyPressed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed
        selecionar();
    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void tabelaItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaItensMouseClicked
        if (evt.getClickCount() == 2) {
            selecionar();
        }
    }//GEN-LAST:event_tabelaItensMouseClicked

    private void tabelaItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaItensKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            selecionar();
        }
    }//GEN-LAST:event_tabelaItensKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ftfPesquisar.setText("");
        ftfPesquisar.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        try {
            aoTrocarAbas();
        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void ftfTotalApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfTotalApagarActionPerformed

    }//GEN-LAST:event_ftfTotalApagarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            Double totalVencido = controle.clienTotalVencido(listaClienPdvBean.get(tabelaItens.getSelectedRow()).getClcodigo(), new java.util.Date());
            Double totalAvencer = controle.clienTotalAvencer(listaClienPdvBean.get(tabelaItens.getSelectedRow()).getClcodigo(), new java.util.Date());
            Double totalApagar = controle.clienTotalApagar(listaClienPdvBean.get(tabelaItens.getSelectedRow()).getClcodigo());

            ftfTotalVencido.setText(Biblioteca.formatarNumero(totalVencido, "#,###,##0.00"));
            ftfTotalAvencer.setText(Biblioteca.formatarNumero(totalAvencer, "#,###,##0.00"));
            ftfTotalApagar.setText(Biblioteca.formatarNumero(totalApagar, "#,###,##0.00"));
            ftfLimiteCredito.setText(Biblioteca.formatarNumero(listaClienPdvBean.get(tabelaItens.getSelectedRow()).getLimitecre(), "#,###,##0.00"));

            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboConsultarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboConsultarItemStateChanged

        Integer opcaoConsulta = comboConsultar.getSelectedIndex();
        String textoLabel = "";

        switch (opcaoConsulta) {
            case 0: {//nome
                textoLabel = "";
            }
            break;
            case 1: {//fantasia
                textoLabel = "";
            }
            break;
            case 2: {//cpf
                textoLabel = "Informe apenas números";
            }
            break;
            case 3: {//cgc
                textoLabel = "Informe apenas números";
            }
            break;
            case 4: {//codigo interno
                textoLabel = "Informe apenas números";
            }
            break;
        }

        jLabel7.setText(textoLabel);

    }//GEN-LAST:event_comboConsultarItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        try {
            obterPadraoPesquisa("FECHAMENTO");
        } catch (IOException ex) {
            Loggin.logDiarioExcecao(ex, true);
        }

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConsultarClientes dialog = new ConsultarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboConsultar;
    private javax.swing.JFormattedTextField ftfLimiteCredito;
    private javax.swing.JFormattedTextField ftfPesquisar;
    private javax.swing.JFormattedTextField ftfTotalApagar;
    private javax.swing.JFormattedTextField ftfTotalAvencer;
    private javax.swing.JFormattedTextField ftfTotalVencido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBotao;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JTable tabelaItens;
    // End of variables declaration//GEN-END:variables
private void consultar() throws SQLException, ClassNotFoundException, IOException, Exception {

        jTabbedPane1.setSelectedIndex(0);

        Integer opcaoConsulta = comboConsultar.getSelectedIndex();

        if (ftfPesquisar.getText() == null || ftfPesquisar.getText().isEmpty()) {
            ftfPesquisar.setText("%%");
        }

        switch (opcaoConsulta) {
            case 0: {//nome
                if (jRadioButton1.isSelected()) {
                    listaClienPdvBean = controle.listarClienPdvNome(ftfPesquisar.getText().trim() + "%");
                } else {
                    listaClienPdvBean = controle.listarClienPdvNome("%" + ftfPesquisar.getText().trim() + "%");
                }
            }
            break;
            case 1: {//fantasia
                if (jRadioButton1.isSelected()) {
                    listaClienPdvBean = controle.listarClienPdvFantasia(ftfPesquisar.getText().trim() + "%");
                } else {
                    listaClienPdvBean = controle.listarClienPdvFantasia("%" + ftfPesquisar.getText().trim() + "%");
                }
            }
            break;
            case 2: {//cpf
                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }
                listaClienPdvBean = controle.listarClienPdvCpf(ftfPesquisar.getText().trim());
            }
            break;
            case 3: {//cgc
                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }
                listaClienPdvBean = controle.listarClienPdvCgc(ftfPesquisar.getText().trim());
            }
            break;
            case 4: {//codigo interno

                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }
                listaClienPdvBean = new ArrayList<ClienPdvBean>();
                clienPdvBean = controle.clienPdvClcodigo(Integer.valueOf(ftfPesquisar.getText().trim()));

                if (clienPdvBean != null) {
                    listaClienPdvBean.add(clienPdvBean);
                }
            }
            break;
        }

        //-------------------------------------
        atualizarTabelaItem(listaClienPdvBean);
    }

    //==============================================================
    void atualizarTabelaItem(List<ClienPdvBean> listaAuxiliarBean) {

        ((DefaultTableModel) tabelaItens.getModel()).setRowCount(0);
        if (listaAuxiliarBean != null && listaAuxiliarBean.size() > 0) {

            for (ClienPdvBean o : listaAuxiliarBean) {
                Object[] linha = {
                    o.getClcodigo(),
                    o.getNome(),
                    o.getCpf(),
                    o.getCgc(),
                    o.getEndereco(),};

                ((DefaultTableModel) tabelaItens.getModel()).addRow(linha);
            }

            tabelaItens.setRowSelectionInterval(0, 0); //da pau quando vazia

            botaoSelecionar.setEnabled(true);
            tabelaItens.requestFocus();

            //rotina abaixo, após consulta o item pelo codigo de barra.
            //já deixa o sistema preparado para próxima consulta automatico,
            //sem que acha intervenção do usuario, desde que a consulta seja por codigo de barra
            //if (Caixa.configuracaoBean.getSegmentoMercado().equalsIgnoreCase("SUPERMERCADO")) {
            if (comboConsultar.getSelectedIndex() == 1) { //codigo barra
                ftfPesquisar.requestFocus();
                //tfPesquisar.selectAll();
                ftfPesquisar.setText("");
            }

        } else {

            ftfPesquisar.requestFocus();
            //tfPesquisar.selectAll();
            ftfPesquisar.setText("");
            botaoSelecionar.setEnabled(false);
        }

    }

    //==================================
    private void formatarTabelaItens() {

        /**
         * ******************************************************************
         **
         ********************************************************************
         */
        tabelaItens.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); //Para mostrar scroll vertical e horizontal: 
        //tabelaItens.getTableHeader().setPreferredSize(new Dimension(1124, 25));
        //tabelaItens.getTableHeader().setFont(new java.awt.Font("Verdana", 0, 15));

        //getMfcodigo
        //tabelaItens.getColumnModel().getColumn(0).setMinWidth(50);
        tabelaItens.getColumnModel().getColumn(0).setMaxWidth(100);
        tabelaItens.getColumnModel().getColumn(0).setPreferredWidth(100);

        //getNome
        tabelaItens.getColumnModel().getColumn(1).setMinWidth(300);
        tabelaItens.getColumnModel().getColumn(1).setMaxWidth(600);
        tabelaItens.getColumnModel().getColumn(1).setPreferredWidth(500);

        //getCpf()
        //tabelaItens.getColumnModel().getColumn(2).setMinWidth(70);
        tabelaItens.getColumnModel().getColumn(2).setMaxWidth(150);
        tabelaItens.getColumnModel().getColumn(2).setPreferredWidth(100);

        //getCgc()
        //tabelaItens.getColumnModel().getColumn(3).setMinWidth(70);
        tabelaItens.getColumnModel().getColumn(3).setMaxWidth(150);
        tabelaItens.getColumnModel().getColumn(3).setPreferredWidth(100);

        //getEndereco()
        //tabelaItens.getColumnModel().getColumn(4).setMinWidth(70);
        tabelaItens.getColumnModel().getColumn(4).setMaxWidth(250);
        //tabelaItens.getColumnModel().getColumn(4).setPreferredWidth(200);

        //ajuste conteudo na celula
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);

        tabelaItens.getColumnModel().getColumn(0).setCellRenderer(direita);
        tabelaItens.getColumnModel().getColumn(1).setCellRenderer(esquerda);
        tabelaItens.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        tabelaItens.getColumnModel().getColumn(3).setCellRenderer(esquerda);
        tabelaItens.getColumnModel().getColumn(4).setCellRenderer(esquerda);

        tabelaItens.setFont(new java.awt.Font("Verdana", 0, 15));
        tabelaItens.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);    // seta o modo de auto-redimensionamento como desligado

        //tabelaItens.setAutoCreateRowSorter(true); //ORDENA AS COLUNAS DE UMA TABELA
    }

    //=========================
    private void selecionar() {

        Integer linhaSelecionada = tabelaItens.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item!", Constantes.AVISO_SISTEMA, JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        clienPdvBean = listaClienPdvBean.get(linhaSelecionada);
        this.dispose();
    }

    private void aoTrocarAbas() throws ClassNotFoundException, IOException, Exception {

        if (jTabbedPane1.getSelectedIndex() == 1) {//consulta credito clientes

            if (tabelaItens.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um cliente para consulta.", Constantes.AVISO_SISTEMA, JOptionPane.INFORMATION_MESSAGE);
                jButton2.setEnabled(false);
                return;
            }

            jButton2.setEnabled(true);
            jLabel2.setText("Cliente: " + listaClienPdvBean.get(tabelaItens.getSelectedRow()).getNome());
            ftfTotalVencido.setText(Biblioteca.formatarNumero(0, "#,###,##0.00"));
            ftfTotalAvencer.setText(Biblioteca.formatarNumero(0, "#,###,##0.00"));
            ftfTotalApagar.setText(Biblioteca.formatarNumero(0, "#,###,##0.00"));
            ftfLimiteCredito.setText(Biblioteca.formatarNumero(0, "#,###,##0.00"));
        }
    }

    //================================================================
    private void obterPadraoPesquisa(String modo) throws IOException {

        String padraoPesquisa;
        Properties arquivoConfig = new Properties();

        if (modo.equalsIgnoreCase("ABERTURA")) {

            arquivoConfig.load(new FileInputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties")));

            padraoPesquisa = arquivoConfig.getProperty("pesquisa.cliente");

            if (padraoPesquisa != null && !padraoPesquisa.isEmpty()) {
                comboConsultar.setSelectedIndex(Integer.parseInt(padraoPesquisa));
            }

        } else {

            padraoPesquisa = String.valueOf(comboConsultar.getSelectedIndex());

            arquivoConfig.load(new FileInputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties")));
            arquivoConfig.setProperty("pesquisa.cliente", padraoPesquisa);
            FileOutputStream out = new FileOutputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties"));
            arquivoConfig.store(out, "");
            out.close();

        }
    }

    //=========================
    private void cancelar() {

        clienPdvBean = null;

        dispose();
        //this.setVisible(false);
        //public void actionPerformed(ActionEvent e) {    
        //    if(e.getSource() == bt_cancela) {    
        //        this.dispose();    
        //    }    
        //}        
    }

    //=========================================================================
    private class SelecionarAction extends AbstractAction {

        public SelecionarAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            selecionar();
        }
    }

    //=========================================================================
    private class CancelarAction extends AbstractAction {

        public CancelarAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            cancelar();
        }
    }
}
