/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visual;

import br.com.controle.Controle;
import br.com.modelo.MaterPdvBean;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul
 */
public class ConsultarItens extends javax.swing.JDialog {

    private final Controle controle = new Controle();
    private MaterPdvBean materPdvBean = new MaterPdvBean();
    List<MaterPdvBean> listaMaterPdvBean = new ArrayList<MaterPdvBean>();

    public MaterPdvBean getMaterPdvBean() {
        return materPdvBean;
    }

    /**
     * Creates new form ConsultarItens
     */
    public ConsultarItens(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ImageIcon icone = new javax.swing.ImageIcon(Constantes.SH_ICONE);
        setIconImage(icone.getImage());

        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); //DESABILITAR tb a função do X do JDialog, para que só seja possível cancelar clicando no seu botão, coloque tb. esse código: 
        CancelarAction cancelarAction = new CancelarAction();
        panelComponentes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancelarAction");
        panelComponentes.getActionMap().put("cancelarAction", cancelarAction);

        SelecionarAction selecionarAction = new SelecionarAction();
        panelComponentes.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "selecionarAction");
        panelComponentes.getActionMap().put("selecionarAction", selecionarAction);

        //-------------------------------------------
        try {
            //------------------------
            jLabel2.setText("");
            formatarTabelaItens();

            //---------------------
            obterPadraoPesquisa("ABERTURA");
        } catch (IOException ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelComponentes = new javax.swing.JPanel();
        panelFiltros = new javax.swing.JPanel();
        ftfPesquisar = new javax.swing.JFormattedTextField();
        comboConsultar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoSelecionar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta de Itens");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro da Consulta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N

        ftfPesquisar.setText(" ");
        ftfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftfPesquisarKeyPressed(evt);
            }
        });

        comboConsultar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descrição", "Código", "Referencia", "Código Interno" }));
        comboConsultar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboConsultarItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel1.setText("Pressione ENTER para consulta");

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Consulta Ordenada");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Consulta \"Palavra Chave\"");

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Und", "Preço", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        tabelaClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(520, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(520, 15));

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFiltrosLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                            .addComponent(ftfPesquisar))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(393, 40));

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.setMaximumSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.setMinimumSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.setPreferredSize(new java.awt.Dimension(150, 30));
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });

        jButton3.setText(" Cancelar");
        jButton3.setMaximumSize(new java.awt.Dimension(150, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelComponentesLayout = new javax.swing.GroupLayout(panelComponentes);
        panelComponentes.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cancelar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void ftfPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfPesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //pressionou ENTER
            try {
                consultar();
            } catch (Exception ex) {
                Loggin.logDiarioExcecao(ex, true);
            }
        }
    }//GEN-LAST:event_ftfPesquisarKeyPressed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed
        selecionar();
    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        if (evt.getClickCount() == 2) {
            selecionar();
        }
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void tabelaClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaClientesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            selecionar();
        }
    }//GEN-LAST:event_tabelaClientesKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ftfPesquisar.setText("");
        ftfPesquisar.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboConsultarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboConsultarItemStateChanged

        Integer opcaoConsulta = comboConsultar.getSelectedIndex();
        String textoLabel = "";

        switch (opcaoConsulta) {
            case 0: { //descricao
                textoLabel = "";
            }
            break;
            case 1: {//codigo
                textoLabel = "Informe apenas números";
            }
            break;
            case 2: {//Referencia
                textoLabel = "";
            }
            break;
            case 3: {//codigo interno
                textoLabel = "Informe apenas números";
            }
            break;
        }

        jLabel2.setText(textoLabel);
    }//GEN-LAST:event_comboConsultarItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        try {
            obterPadraoPesquisa("FECHAMENTO");
        } catch (IOException ex) {
            Loggin.logDiarioExcecao(ex, true);
        }

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConsultarItens dialog = new ConsultarItens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboConsultar;
    private javax.swing.JFormattedTextField ftfPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
private void consultar() throws SQLException, ClassNotFoundException, IOException, Exception {

        Integer opcaoConsulta = comboConsultar.getSelectedIndex();
        if (ftfPesquisar.getText() == null || ftfPesquisar.getText().isEmpty()) {
            ftfPesquisar.setText("%%");
        }
        switch (opcaoConsulta) {
            case 0: {//descricao

                if (jRadioButton1.isSelected()) {
                    listaMaterPdvBean = controle.listarMaterPdvNome(ftfPesquisar.getText().trim() + "%");
                } else {
                    listaMaterPdvBean = controle.listarMaterPdvNome("%" + ftfPesquisar.getText().trim() + "%");
                }

            }
            break;
            case 1: {//codigo barra: Mfcodigo
                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }

                materPdvBean = controle.materPdvMfcodigo(ftfPesquisar.getText().trim());

                listaMaterPdvBean = new ArrayList<>();
                listaMaterPdvBean.add(materPdvBean);
            }
            break;
            case 2: {//referencia
                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }

                if (jRadioButton1.isSelected()) {
                    listaMaterPdvBean = controle.listarMaterPdvReferencia(ftfPesquisar.getText().trim() + "%");
                } else {
                    listaMaterPdvBean = controle.listarMaterPdvReferencia("%" + ftfPesquisar.getText().trim() + "%");
                }
            }
            break;
            case 3: {//codigo interno
                if (ftfPesquisar.getText().isEmpty()) {
                    return;
                }

                listaMaterPdvBean = new ArrayList<>();
                materPdvBean = controle.materPdvCodIntern(ftfPesquisar.getText().trim());

                if (materPdvBean != null) {
                    listaMaterPdvBean.add(materPdvBean);
                }
            }
            break;
        }

        //-------------------------------------
        atualizarTabelaItem(listaMaterPdvBean);
    }

    //==============================================================
    void atualizarTabelaItem(List<MaterPdvBean> listaAuxiliarBean) {

        ((DefaultTableModel) tabelaClientes.getModel()).setRowCount(0);
        if (listaAuxiliarBean != null && listaAuxiliarBean.size() > 0) {

            for (MaterPdvBean o : listaAuxiliarBean) {
                Object[] linha = {
                    o.getMfcodigo(),
                    o.getNome(),
                    o.getUnidadeVO().getUncodigo(),
                    Biblioteca.formatarNumero(Biblioteca.truncar(o.getPrecoven(), 2), "#,###,##0.00"),
                    Biblioteca.formatarNumero(o.getQtdestoq(), "#,###,##0.00")};

                ((DefaultTableModel) tabelaClientes.getModel()).addRow(linha);
            }

            tabelaClientes.setRowSelectionInterval(0, 0); //da pau quando vazia

            botaoSelecionar.setEnabled(true);
            tabelaClientes.requestFocus();

            //rotina abaixo, após consulta o item pelo codigo de barra.
            //já deixa o sistema preparado para próxima consulta automatico,
            //sem que acha intervenção do usuario, desde que a consulta seja por codigo de barra
            //if (Caixa.configuracaoBean.getSegmentoMercado().equalsIgnoreCase("SUPERMERCADO")) {
            if (comboConsultar.getSelectedIndex() == 1) { //codigo barra
                ftfPesquisar.requestFocus();
                //tfPesquisar.selectAll();
                ftfPesquisar.setText("");
            }

        } else {

            ftfPesquisar.requestFocus();
            //tfPesquisar.selectAll();
            ftfPesquisar.setText("");
            botaoSelecionar.setEnabled(false);
        }

    }

    //==================================
    private void formatarTabelaItens() {

        /**
         * ******************************************************************
         **
         ********************************************************************
         */
        tabelaClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); //Para mostrar scroll vertical e horizontal: 
        //tabelaItens.getTableHeader().setPreferredSize(new Dimension(1124, 25));
        //tabelaItens.getTableHeader().setFont(new java.awt.Font("Verdana", 0, 15));

        //getMfcodigo
        //tabelaItens.getColumnModel().getColumn(0).setMinWidth(50);
        tabelaClientes.getColumnModel().getColumn(0).setMaxWidth(100);
        tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(100);

        //getNome
        tabelaClientes.getColumnModel().getColumn(1).setMinWidth(300);
        tabelaClientes.getColumnModel().getColumn(1).setMaxWidth(800);
        tabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(700);

        //getUnidadeVO().getUncodigo()
        //tabelaItens.getColumnModel().getColumn(2).setMinWidth(50);
        tabelaClientes.getColumnModel().getColumn(2).setMaxWidth(75);
        tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(50);

        //getPrecoven
        //tabelaItens.getColumnModel().getColumn(3).setMinWidth(70);
        tabelaClientes.getColumnModel().getColumn(3).setMaxWidth(70);
        //tabelaItens.getColumnModel().getColumn(3).setPreferredWidth(70);

        //getQtdestoq
        //tabelaItens.getColumnModel().getColumn(4).setMinWidth(70);
        tabelaClientes.getColumnModel().getColumn(4).setMaxWidth(70);
        //tabelaItens.getColumnModel().getColumn(4).setPreferredWidth(70);

        //ajuste conteudo na celula
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();

        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);

        tabelaClientes.getColumnModel().getColumn(0).setCellRenderer(direita);
        tabelaClientes.getColumnModel().getColumn(1).setCellRenderer(esquerda);
        tabelaClientes.getColumnModel().getColumn(2).setCellRenderer(esquerda);
        tabelaClientes.getColumnModel().getColumn(3).setCellRenderer(direita);
        tabelaClientes.getColumnModel().getColumn(4).setCellRenderer(direita);

        tabelaClientes.setFont(new java.awt.Font("Verdana", 0, 15));
        tabelaClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);    // seta o modo de auto-redimensionamento como desligado

        //tabelaItens.setAutoCreateRowSorter(true); //ORDENA AS COLUNAS DE UMA TABELA
    }

    //=========================
    private void selecionar() {

        Integer linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um item!", Constantes.AVISO_SISTEMA, JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        materPdvBean = listaMaterPdvBean.get(linhaSelecionada);
        this.dispose();
    }

    //================================================================
    private void obterPadraoPesquisa(String modo) throws IOException {

        String padraoPesquisa;
        Properties arquivoConfig = new Properties();

        if (modo.equalsIgnoreCase("ABERTURA")) {

            arquivoConfig.load(new FileInputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties")));

            padraoPesquisa = arquivoConfig.getProperty("pesquisa.item");

            if (padraoPesquisa != null && !padraoPesquisa.isEmpty()) {
                comboConsultar.setSelectedIndex(Integer.parseInt(padraoPesquisa));
            }

        } else {

            padraoPesquisa = String.valueOf(comboConsultar.getSelectedIndex());

            arquivoConfig.load(new FileInputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties")));
            arquivoConfig.setProperty("pesquisa.item", padraoPesquisa);
            try (FileOutputStream out = new FileOutputStream(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties"))) {
                arquivoConfig.store(out, "");
            }

        }
    }

    //=========================
    private void cancelar() {

        materPdvBean = null;
        dispose();
        //this.setVisible(false);
        //public void actionPerformed(ActionEvent e) {    
        //    if(e.getSource() == bt_cancela) {    
        //        this.dispose();    
        //    }    
        //}        
    }

    //=========================================================================
    private class SelecionarAction extends AbstractAction {

        public SelecionarAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            selecionar();
        }
    }

    //=========================================================================
    private class CancelarAction extends AbstractAction {

        public CancelarAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            cancelar();
        }
    }
}
