/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visual;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Raul
 */
public class MenuOpcoes extends javax.swing.JDialog {

    /**
     * Creates new form MenuOpcoes
     */
    public MenuOpcoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ImageIcon icone = new javax.swing.ImageIcon(Constantes.SH_ICONE);
        setIconImage(icone.getImage());

        //TECLA A
        AAction aAction = new AAction();
        jButton1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_A, 0), "AAction");
        jButton1.getActionMap().put("AAction", aAction);

        //TECLA B
        BAction bAction = new BAction();
        jButton5.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_B, 0), "BAction");
        jButton5.getActionMap().put("BAction", bAction);

        //TECLA C
        CAction cAction = new CAction();
        jButton3.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_C, 0), "CAction");
        jButton3.getActionMap().put("CAction", cAction);

        //TECLA D
        DAction dAction = new DAction();
        jButton4.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_D, 0), "DAction");
        jButton4.getActionMap().put("DAction", dAction);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu de Opções");
        setMinimumSize(new java.awt.Dimension(300, 350));

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Consulta de Vendas <A>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Consulta de Orçamentos <B>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Acesso Banco de Dados <C>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Configurações <D>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ConsultarVendas movimentacaoVendas = new ConsultarVendas(new JFrame(), true);
        movimentacaoVendas.setResizable(false);
        movimentacaoVendas.setModal(true);
        movimentacaoVendas.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        AcessoUsuario acessoUsuario = new AcessoUsuario(new JFrame(), true);
        acessoUsuario.setResizable(false);
        acessoUsuario.setModal(true);
        acessoUsuario.setVisible(true);
        if (acessoUsuario.getFuncionaBean() == null || !acessoUsuario.getFuncionaBean().getTfcodigo().equalsIgnoreCase("G")) {
            //JOptionPane.showMessageDialog(this, "É necessario privilegio de gerente para acessar esse módulo.", Constantes.AVISO_SISTEMA, JOptionPane.INFORMATION_MESSAGE);
            //return;
        }

        //---------------------------------------------------------------
        Configuracao configuracao = new Configuracao(new JFrame(), true);
        configuracao.setResizable(false);
        configuracao.setModal(true);
        configuracao.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ConfigurarAcessoBD configurarAcesso = new ConfigurarAcessoBD(new JFrame(), true);
        configurarAcesso.setResizable(false);
        configurarAcesso.setModal(true);
        configurarAcesso.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //consulta de orçamento
        ConsultarOrcamentos consultarOrcamentos = new ConsultarOrcamentos(new JFrame(), true);
        consultarOrcamentos.setResizable(false);
        consultarOrcamentos.setModal(true);
        consultarOrcamentos.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Loggin.logDiarioExcecao(ex, true);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuOpcoes dialog = new MenuOpcoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //***************************************************************************
    private class AAction extends AbstractAction {

        public AAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            jButton1ActionPerformed(null);
        }
    }

    //***************************************************************************
    private class CAction extends AbstractAction {

        public CAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            jButton3ActionPerformed(null);
        }
    }

    //***************************************************************************
    private class DAction extends AbstractAction {

        public DAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            jButton4ActionPerformed(null);
        }
    }

    //***************************************************************************
    private class BAction extends AbstractAction {

        public BAction() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            jButton5ActionPerformed(null);
        }
    }

}
